Yemek:
CREATE TABLE "public"."Yemek" ( 
"adi" Character Varying NOT NULL, 
"Yemek_id" Integer DEFAULT nextval('yemek_id_seq'::regclass) NOT NULL,
"Yemek_Kategori_id" Integer NOT NULL,
"Resim_id" Integer, 
PRIMARY KEY ( "Yemek_id" ) );
CREATE INDEX "index_Yemek_Kategori_id" ON "public"."Yemek" USING btree( "Yemek_Kategori_id" Asc NULLS Last );
CREATE INDEX "index_Resim_id1" ON "public"."Yemek" USING btree( "Resim_id" Asc NULLS Last ); 
ALTER TABLE "public"."Yemek"
ADD CONSTRAINT "lnk_Resim_Yemek" FOREIGN KEY ( "Resim_id" )
REFERENCES "public"."Resim" ( "Resim_id" ) MATCH FULL
ON DELETE Set Default
ON UPDATE No Action;

ALTER TABLE "public"."Yemek"
ADD CONSTRAINT "lnk_Yemek_Kategori_Yemek_3" FOREIGN KEY ( "Yemek_Kategori_id" )
REFERENCES "public"."Yemek_Kategori" ( "Yemek_Kategori_id" ) MATCH FULL
ON DELETE Set Default
ON UPDATE No Action;
INSERT INTO "public"."Yemek" (adi, "Yemek_id", "Yemek_Kategori_id", "Resim_id") 
VALUES
('Yoğurt Çorbası', nextval('yemek_id_seq'::regclass), 1, NULL),
('Patlıcan Musakka', nextval('yemek_id_seq'::regclass), 2, NULL),
('Domates Çorbası', nextval('yemek_id_seq'::regclass), 1, NULL),
('Mantar Çorbası', nextval('yemek_id_seq'::regclass), 1, NULL),
('Sebze Çorbası', nextval('yemek_id_seq'::regclass), 1, NULL),
('Mercimek Çorbası', nextval('yemek_id_seq'::regclass), 1, NULL),
('Mısır Çorbası', nextval('yemek_id_seq'::regclass), 1, NULL),
('Nohutlu Çorba', nextval('yemek_id_seq'::regclass), 1, NULL),
('Kırmızı Mercimek Çorbası', nextval('yemek_id_seq'::regclass), 1, NULL),
('Et Sote', nextval('yemek_id_seq'::regclass), 2, NULL),
('Zeytinyağlı Patlıcan', nextval('yemek_id_seq'::regclass), 2, NULL),
('Tavuk Sote', nextval('yemek_id_seq'::regclass), 2, NULL),
('Patatesli Köfte', nextval('yemek_id_seq'::regclass), 2, NULL),
('Hamsi Tava', nextval('yemek_id_seq'::regclass), 2, NULL),
('Nohut Yemeği', nextval('yemek_id_seq'::regclass), 2, NULL),
('Kıymalı Fasulye', nextval('yemek_id_seq'::regclass), 2, NULL),
('Elmalı Tatlı', nextval('yemek_id_seq'::regclass), 3, NULL),
('Çilekli Bisküvili Tatlı', nextval('yemek_id_seq'::regclass), 3, NULL),
('Muzlu Sütlü Tatlı', nextval('yemek_id_seq'::regclass), 3, NULL),
('Yoğurt Tatlısı', nextval('yemek_id_seq'::regclass), 3, NULL),
('Çilekli Sütlü Tatlı', nextval('yemek_id_seq'::regclass), 3, NULL),
('Kakaolu Bisküvili Tatlı', nextval('yemek_id_seq'::regclass), 3, NULL),
('Muzlu Tatlı', nextval('yemek_id_seq'::regclass), 3, NULL),
('Çoban Salata', nextval('yemek_id_seq'::regclass), 4, NULL),
('Zeytinyağlı Salata', nextval('yemek_id_seq'::regclass), 4, NULL),
('Yoğurtlu Salata', nextval('yemek_id_seq'::regclass), 4, NULL),
('Patates Salatası', nextval('yemek_id_seq'::regclass), 4, NULL),
('Havuç Salatası', nextval('yemek_id_seq'::regclass), 4, NULL),
('Domatesli Salata', nextval('yemek_id_seq'::regclass), 4, NULL),
('Marul Salatası', nextval('yemek_id_seq'::regclass), 4, NULL);

Tarif:
CREATE TABLE "public"."Tarif" ( 
"tarif_adi" Character Varying NOT NULL,
"yapilisi" Text NOT NULL,
"tarih" Date NOT NULL,
"Yemek_id" Integer NOT NULL,
"Tarif_id" Integer
 GENERATED BY DEFAULT AS IDENTITY (
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
),
"ortalama_puan" Integer,
"son_guncelleme" Timestamp With Time Zone,
"pisirme_gereci_id" Integer,
PRIMARY KEY ( "Tarif_id" ) );

INSERT INTO "Tarif"(Tarif_id, tarif_adi, yapilisi, Yemek_id, tarih, ortalama_puan, pisirme_gereci_id, son_guncelleme) 
VALUES
(1, ‘Enfes Yoğurt Çorbası’, 'Suyu kaynatın, pirinci ekleyin, yoğurt ve yumurta ile çırpın, tuz ve nane ile tatlandırın.', 1, NOW( ), 4 , 2,  NULL)
(2, ‘Leziz Patlıcan Musakka’, 'Patlıcanları kızartın, kıymayı kavurun, domates ve baharat ekleyin, kat kat dizin ve fırınlayın.', 2, NOW(), 1, 1, NULL)
(3, 'Domates Çorbası', 'Domates tereyağ ile kavrulur, un eklenir, su eklenip kaynatılır.',3, NOW(), 0, 2, NULL),
(4, 'Mantar Çorbası', 'Mantar sotelenip süt, un ve tereyağı ile pişirilir.', 4, NOW(), 0, 2, NULL),
(5, 'Sebze Çorbası', 'Patates, havuç, biber ve domates kaynatılır, nane eklenir.', 5, NOW(), 0, 2, NULL),
(6, 'Mercimek Çorbası', 'Mercimek, un ve yağ ile kaynatılır, limonla servis edilir.', 6, NOW(), 0, 2, NULL),
(7, 'Mısır Çorbası', 'Mısır süt ve tereyağı ile pişirilir.', 7, NOW(), 0, 2, NULL),
(8, 'Nohutlu Çorba', 'Nohut salça ve nane ile kaynatılır.', 8, NOW(), 0, 2, NULL),
(9, 'Kırmızı Mercimek Çorbası', 'Mercimek biber salçası ile pişirilir.', 9, NOW(), 0, 1, NULL),
(10, 'Et Sote', 'Et, soğan ve biber kavrulur; salça eklenip pişirilir.', 10, NOW(), 0, 1, NULL),
(11, 'Zeytinyağlı Patlıcan', 'Patlıcan, soğan ve domates zeytinyağı ile pişirilir.', 11, NOW(), 0, 1, NULL),
(12, 'Tavuk Sote', 'Tavuk soğan ve biber ile sotelenir, kekik eklenir.', 12, NOW(), 0, 1, NULL),
(13, 'Patatesli Köfte', 'Kıyma patates ve soğanla yoğrulur, pişirilir.', 13, NOW(), 0, 4, NULL),
(14, 'Hamsi Tava', 'Balık una bulanır ve kızartılır.', 14, NOW(), 0, 1, NULL),
(15, 'Nohut Yemeği', 'Nohut soğanla kavrulup salça eklenerek pişirilir.', 15, NOW(), 0, 3, NULL),
(16, 'Kıymalı Fasulye', 'Fasulye kıyma ve salça ile pişirilir.', 16, NOW(), 0, 1, NULL)
(17, 'Elmalı Tatlı', 'Elma rendelenir, bisküvi ile karıştırılarak servis edilir.', 17, NOW(), 0, 5, NULL),
(18, 'Çilekli Bisküvili Tatlı', 'Çilek süt ve bisküvi ile hazırlanır, vanilya eklenir.', 18, NOW(), 0, 2, NULL),
(19, 'Muzlu Sütlü Tatlı', 'Muz süt ve nişasta ile pişirilir.', 19, NOW(), 0, 2, NULL),
(20, 'Yoğurt Tatlısı', 'Yoğurt, un ve yumurta ile karıştırılıp pişirilir.', 20, NOW(), 0, 4, NULL),
(21, 'Çilekli Sütlü Tatlı', 'Çilek süt ve nişasta ile pişirilir.', 21, NOW(), 0, 2, NULL),
(22, 'Kakaolu Bisküvili Tatlı', 'Kakao süt ve bisküvi ile hazırlanır.', 22, NOW(), 0, 2, NULL),
(23, 'Muzlu Tatlı', 'Muz süt ve bisküvi ile tatlı yapılır.', 23, NOW(), 0, 2, NULL);
(24, 'Çoban Salata', 'Domates, salatalık, soğan ve limon ile hazırlanır.', 24, NOW(), 0, 5, NULL),
(25, 'Zeytinyağlı Salata', 'Marul zeytinyağı ve limonla karıştırılır.', 25, NOW(), 0, 5, NULL),
(26, 'Yoğurtlu Salata', 'Marul yoğurt ve limon ile karıştırılır.', 26, NOW(), 0, 5, NULL),
(27, 'Patates Salatası', 'Patates soğan ve nane ile karıştırılır.', 27, NOW(), 0, 5, NULL),
(28, 'Havuç Salatası', 'Havuç yoğurtla karıştırılır.', 28, NOW(), 0, 5, NULL),
(29, 'Domatesli Salata', 'Domates soğan ve nane ile hazırlanır.', 29, NOW(), 0, 5, NULL),
(30, 'Marul Salatası', 'Marul limon ve tuz ile karıştırılır.', 30, NOW(), 0, 5, NULL);
 ;
Yemek_Kategori:
CREATE TABLE "public"."Yemek_Kategori" ( 
"kategori_adi" Character Varying NOT NULL,
"Yemek_Kategori_id" Integer NOT NULL,
PRIMARY KEY ( "Yemek_Kategori_id" ) );
 ;
INSERT INTO "public"."Yemek_Kategori" (“Yemek_Kategori_id”, kategori_adi) 
VALUES
(1, 'Çorba'),
(2, 'Ana Yemek'),
(3, 'Tatlı'),
(4, 'Salata');
Bölge:
CREATE TABLE "public"."Bölge" ( 
"Bölge_adı" Character( 25 ) NOT NULL,
"Bölge_id" Integer NOT NULL,
PRIMARY KEY ( "Bölge_id" ) );
 ;
INSERT INTO "public"."Bölge" (Bölge_id, Bölge_adı) 
VALUES
(1, 'Karadeniz’),
(2, ‘İç Anadolu’),
(3, ‘Marmara’),
(4, ‘Ege’'),
(5, 'Akdeniz'),
(6, 'Doğu Anadolu'),
(7, 'Güneydoğu Anadolu');
Malzeme_Kategori:
CREATE TABLE "public"."Malzeme_Kategori" ( 
"Malzeme_Kategori_id" Integer NOT NULL,
"malzeme_kategori_adi" Character Varying NOT NULL,
PRIMARY KEY ( "Malzeme_Kategori_id" ) );
;
INSERT INTO "public"."Malzeme_Kategori" (Malzeme_Kategori_id, malzeme_kategori_adi) 
VALUES
(1, 'Sebze'),
(2, 'Meyve'),
(3, 'Et'),
(4, 'Hayvansal Gıda'),
(5, 'Salça'),
(6, 'Baharat'),
(7, 'Yağ'),
(8, 'Tahıl'),
(9, 'Kurubaklagil'),
(10, 'Sıvı'),
(11, 'Tatlı');
Malzeme:
CREATE TABLE "public"."Malzeme" ( 
"malzeme_adi" Character Varying NOT NULL,
"Malzeme_id" Integer DEFAULT nextval('malzeme_id_seq'::regclass) NOT NULL,
"Malzeme_Kategori_id" Integer NOT NULL,
PRIMARY KEY ( "Malzeme_id" ) );
 ;
CREATE INDEX "index_Malzeme_Kategori_id" ON "public"."Malzeme" USING btree( "Malzeme_Kategori_id" Asc NULLS Last );
INSERT INTO "public"."Malzeme" (Malzeme_id, malzeme_adi, Malzeme_Kategori_id) 
VALUES
(nextval('malzeme_id_seq'::regclass), 'Patates', 1),
(nextval('malzeme_id_seq'::regclass), 'Soğan', 1),
(nextval('malzeme_id_seq'::regclass), 'Patlıcan', 1),
(nextval('malzeme_id_seq'::regclass), 'Havuç', 1),
(nextval('malzeme_id_seq'::regclass), 'Biber', 1),
(nextval('malzeme_id_seq'::regclass), 'Marul', 1),
(nextval('malzeme_id_seq'::regclass), 'Domates', 1),
(nextval('malzeme_id_seq'::regclass), 'Salatalık', 1), 
(nextval('malzeme_id_seq'::regclass), 'Çilek', 2),
(nextval('malzeme_id_seq'::regclass), 'Muz', 2),
(nextval('malzeme_id_seq'::regclass), 'Elma', 2),
(nextval('malzeme_id_seq'::regclass), 'Kırmızı Et', 3),
(nextval('malzeme_id_seq'::regclass), 'Tavuk', 3),
(nextval('malzeme_id_seq'::regclass), 'Balık', 3), 
(nextval('malzeme_id_seq'::regclass), 'Süt', 4),
(nextval('malzeme_id_seq'::regclass), 'Peynir', 4),
(nextval('malzeme_id_seq'::regclass), 'Yoğurt', 4),
(nextval('malzeme_id_seq'::regclass), 'Yumurta', 4), 
(nextval('malzeme_id_seq'::regclass), 'Domates Salçası', 5),
(nextval('malzeme_id_seq'::regclass), 'Biber Salçası', 5),
(nextval('malzeme_id_seq'::regclass), 'Tuz', 6),
(nextval('malzeme_id_seq'::regclass), 'Karabiber', 6),
(nextval('malzeme_id_seq'::regclass), 'Kırmızıbiber', 6),
(nextval('malzeme_id_seq'::regclass), ' Vanilya Tozu',8),
(nextval('malzeme_id_seq'::regclass), 'Nane', 6),
(nextval('malzeme_id_seq'::regclass), 'Kekik', 6),
(nextval('malzeme_id_seq'::regclass), 'Zeytinyağı', 7),
(nextval('malzeme_id_seq'::regclass), 'Ayçiçekyağı', 7),
(nextval('malzeme_id_seq'::regclass), 'Tereyağı', 7), 
(nextval('malzeme_id_seq'::regclass), 'Un', 8),
(nextval('malzeme_id_seq'::regclass), 'Nişasta', 8),
(nextval('malzeme_id_seq'::regclass), 'Mercimek', 9),
(nextval('malzeme_id_seq'::regclass), 'Nohut', 9),
(nextval('malzeme_id_seq'::regclass), 'Fasulye', 9),
(nextval('malzeme_id_seq'::regclass), 'Pirinç', 9);
(nextval('malzeme_id_seq'::regclass), 'Mısır', 1);
(nextval('malzeme_id_seq'::regclass), 'Kakao',8);
(nextval('malzeme_id_seq'::regclass), 'Mantar',1);
(nextval('malzeme_id_seq'::regclass), 'Limon',1);
(nextval('malzeme_id_seq'::regclass), 'Bisküvi',8);
(nextval('malzeme_id_seq'::regclass), 'Kıyma',3);
(nextval('malzeme_id_seq'::regclass), 'Su',10);
(nextval('malzeme_id_seq'::regclass), 'Şeker',11);
(nextval('malzeme_id_seq'::regclass), 'Tarçın', 6);
(nextval('malzeme_id_seq'::regclass), 'Fındık',9);
 
Tarif_Malzeme: 
CREATE TABLE "public"."Tarif_Malzeme" ( "Malzeme_id" Integer NOT NULL, "Tarif_id" Integer NOT NULL); ;
INSERT INTO "public"."Tarif_Malzeme" (Malzeme_id, Tarif_id) 
VALUES
(17, 1),(21, 1),(18, 1),(35, 1),(25, 1),
(22, 2),(27, 2),(21, 2),(2, 2),(3, 2),(41, 2),(7, 2),
(22, 3),(21, 3),(30, 3),(7, 3),(29, 3),(42, 3),
(38, 4),(42, 4),(21, 4),(29, 4),(15, 4),(30, 4),
(7, 5),(1, 5),(21, 5),(25, 5),(42, 5),(5, 5),(4, 5),
(29, 6),(32, 6),(42, 6),(39, 6),(21, 6),(30, 6),
(15, 7),(36, 7),(42, 7),(21, 7),(29, 7),
(21, 8),(25, 8),(19, 8),(33, 8),(42, 8),
(42, 9),(32, 9),(20, 9),(28, 9),(19, 9),(12, 9),(5, 9),
(27, 11),(7, 11),(21, 11),(2, 11),(3, 11),
(28, 12),(21, 12),(13, 12),(5, 12),(2, 12),(26, 12),
(21, 13),(41, 13),(1, 13),(2, 13),(22, 13),
(14, 14),(30, 14),(21, 14),(28, 14),
(2, 15),(19, 15),(42, 15),(29, 15),(33, 15),(34, 15),(19, 15),(2, 15),(41, 15),
(43, 17),(11, 17),(44, 17),(40, 17),
(24, 18),(15, 18),(9, 18),(40, 18),
(24, 19),(31, 19),(15, 19),(10, 19),
(43, 20),(18, 20),(30, 20),(17, 20),(28, 20),
(43, 21),(35, 21),(15, 21),(44, 21),(31, 21),
(40, 22),(15, 22),(37, 22),
(40, 23),(15, 23),(10, 23),
(5, 24),(27, 24),(39, 24),(7, 24),(8, 24),(2, 24),
(27, 25),(39, 25),(7, 25),(6, 25),(17, 25),(8, 25),(6, 25),
(2, 27),(39, 27),(25, 27),(1, 27),
(17, 28),(21, 28),(27, 28),(4, 28),
(2, 29),(25, 29),(27, 29),(7, 29),
(39, 30),(21, 30),(7, 30),(8, 30),(6, 30);
Pisirme_Gereci:
CREATE TABLE "public"."Pisirme_Gereci" ( 
"pisirme_gereci_adi" Character Varying NOT NULL,
"p_gereci_id" Integer DEFAULT nextval('"Pisirme_Gereci_p_gereci_id_seq"'::regclass) NOT NULL,
PRIMARY KEY ( "p_gereci_id" ),
CONSTRAINT "unique_Pisirme_Gereci_p_gereci_id" UNIQUE( "p_gereci_id" ) ); ;
INSERT INTO "public"."Pisirme_Gereci" (pisirme_gereci_adi) 
VALUES
('Tava'), 
('Tencere'),
('Düdüklü Tencere'),
('Fırın'),
('Pişmez / Elde'); 
Resim:
CREATE TABLE "public"."Resim" ( 
"Resim_id" Integer DEFAULT nextval('"Resim_Resim_id_seq"'::regclass) NOT NULL,
"resim_link" JSON NOT NULL,
PRIMARY KEY ( "Resim_id" ) ); 
Bölge_Yemek:
CREATE TABLE "public"."tbl_Bölge_MM_Yemek" ( 
"Bölge_id" Integer NOT NULL,
"Yemek_id" Integer NOT NULL ); ;
ALTER TABLE "public"."tbl_Bölge_MM_Yemek"
ADD CONSTRAINT "lnk_Yemek_MM_Bölge" FOREIGN KEY ( "Yemek_id" )
REFERENCES "public"."Yemek" ( "Yemek_id" ) MATCH FULL
ON DELETE Set Default
ON UPDATE No Action;
ALTER TABLE "public"."tbl_Bölge_MM_Yemek"
ADD CONSTRAINT "lnk_Bölge_MM_Yemek" FOREIGN KEY ( "Bölge_id" )
REFERENCES "public"."Bölge" ( "Bölge_id" ) MATCH FULL
ON DELETE Set Default
ON UPDATE No Action;
INSERT INTO "public"."tbl_Bölge_MM_Yemek" (Yemek_id, Bölge_id) 
VALUES
(nextval('yemek_id_seq'::regclass), 2),  -- Yoğurt Çorbası
(nextval('yemek_id_seq'::regclass), 2),  -- Patlıcan Musakka
(nextval('yemek_id_seq'::regclass), 3),  -- Domates Çorbası
(nextval('yemek_id_seq'::regclass), 4),  -- Mantar Çorbası
(nextval('yemek_id_seq'::regclass), 5),  -- Sebze Çorbası
(nextval('yemek_id_seq'::regclass), 2),  -- Mercimek Çorbası
(nextval('yemek_id_seq'::regclass), 1),  -- Mısır Çorbası
(nextval('yemek_id_seq'::regclass), 6),  -- Nohutlu Çorba
(nextval('yemek_id_seq'::regclass), 7),  -- Kırmızı Mercimek Çorbası
(nextval('yemek_id_seq'::regclass), 3),  -- Et Sote
(nextval('yemek_id_seq'::regclass), 4),  -- Zeytinyağlı Patlıcan
(nextval('yemek_id_seq'::regclass), 5),  -- Tavuk Sote
(nextval('yemek_id_seq'::regclass), 2),  -- Patatesli Köfte
(nextval('yemek_id_seq'::regclass), 1),  -- Hamsi Tava
(nextval('yemek_id_seq'::regclass), 6),  -- Nohut Yemeği
(nextval('yemek_id_seq'::regclass), 7),  -- Kıymalı Fasulye
(nextval('yemek_id_seq'::regclass), 3),  -- Elmalı Tatlı
(nextval('yemek_id_seq'::regclass), 4),  -- Çilekli Bisküvili Tatlı
(nextval('yemek_id_seq'::regclass), 5),  -- Muzlu Sütlü Tatlı
(nextval('yemek_id_seq'::regclass), 2),  -- Yoğurt Tatlısı
(nextval('yemek_id_seq'::regclass), 1),  -- Çilekli Sütlü Tatlı
(nextval('yemek_id_seq'::regclass), 6),  -- Kakaolu Bisküvili Tatlı
(nextval('yemek_id_seq'::regclass), 7),  -- Muzlu Tatlı
(nextval('yemek_id_seq'::regclass), 3),  -- Çoban Salata
(nextval('yemek_id_seq'::regclass), 4),  -- Zeytinyağlı Salata
(nextval('yemek_id_seq'::regclass), 5),  -- Yoğurtlu Salata
(nextval('yemek_id_seq'::regclass), 2),  -- Patates Salatası
(nextval('yemek_id_seq'::regclass), 1),  -- Havuç Salatası
(nextval('yemek_id_seq'::regclass), 6),  -- Domatesli Salata
(nextval('yemek_id_seq'::regclass), 7);  -- Marul Salatası
Log:
CREATE TABLE "public"."Log" ( 
"log_id" Integer DEFAULT nextval('"Log_log_id_seq"'::regclass) NOT NULL,
"kisino" Integer NOT NULL,
"tablo_adi" Character Varying( 50 ) NOT NULL,
"islem_tipi" Character Varying( 20 ) NOT NULL,
"eski_veri" Text,
"yeni_veri" Text,
"tarih" Timestamp Without Time Zone DEFAULT now(),
PRIMARY KEY ( "log_id" ) );;
Yorum:
CREATE TABLE "public"."Yorum" ( 
	"Yorum_id" Integer DEFAULT nextval('"Yorum_yorum_id_seq"'::regclass) NOT NULL,
	"yorum_metni" Text NOT NULL,
	"yorum_tarihi" Timestamp Without Time Zone DEFAULT now() NOT NULL,
	"puan" SmallInt NOT NULL,
	"Tarif_id" Integer NOT NULL,
	"kisino" Integer NOT NULL,
	PRIMARY KEY ( "Yorum_id" ),
	CONSTRAINT "Yorum_puan_check" CHECK(puan >= 1 AND puan <= 5) );
 ;

CREATE INDEX "index_Tarif_id" ON "public"."Yorum" USING btree( "Tarif_id" Asc NULLS Last );
CREATE TRIGGER tg_kufur BEFORE INSERT ON "public"."Yorum" FOR EACH ROW EXECUTE FUNCTION trg_kufur();
CREATE TRIGGER set_yorum_timestamp BEFORE INSERT ON "public"."Yorum" FOR EACH ROW EXECUTE FUNCTION trg_set_yorum_timestamp();
CREATE TRIGGER yorum_puan AFTER INSERT ON "public"."Yorum" FOR EACH ROW EXECUTE FUNCTION trg_yorum_puan();
COMMIT;
BEGIN;
-- CREATE LINK "fk_yorum_uye" ----------------------------------
ALTER TABLE "public"."Yorum"
	ADD CONSTRAINT "fk_yorum_uye" FOREIGN KEY ( "kisino" )
	REFERENCES "public"."uye" ( "kisino" ) MATCH SIMPLE
	ON DELETE Cascade
	ON UPDATE No Action;
COMMIT;
BEGIN;
-- CREATE LINK "fk_yorum_tarif" --------------------------------
ALTER TABLE "public"."Yorum"
	ADD CONSTRAINT "fk_yorum_tarif" FOREIGN KEY ( "Tarif_id" )
	REFERENCES "public"."Tarif" ( "Tarif_id" ) MATCH SIMPLE
	ON DELETE Cascade
	ON UPDATE No Action;
-- -------------------------------------------------------------
Kisi:
CREATE TABLE "public"."kisi" ( 
"kisino" Integer DEFAULT nextval('kisi_kisino_seq'::regclass) NOT NULL,
"ad" Character Varying NOT NULL,
"soyad" Character Varying NOT NULL,
"email" Character Varying NOT NULL,
"sifre" Character Varying NOT NULL,
PRIMARY KEY ( "kisino" ),
CONSTRAINT "kisi_email_key" UNIQUE( "email" ) ); ;
INSERT INTO "public"."kisi" (ad, soyad, email, sifre) 
VALUES
('Serap', 'Çınar', 'serapcinar@gmail.com', 'SC456'),
('Ali', 'Yılmaz', 'aliyılmaz@gmail.com', 'AY123'),
('Kübra', 'Tekin', 'kübratekin@gmail.com', 'KT789'),
('Merve', 'Deniz', 'mervedeniz@gmail.com', 'MD012'),
('Aslı', 'Seçkin', 'asliseckin@gmail.com', 'AS345');
Admin: (kisino=1 )
CREATE TABLE "public"."admin" ( 
"kisino" Integer DEFAULT nextval('kisi_kisino_seq'::regclass) NOT NULL,
"ad" Character Varying NOT NULL,
"soyad" Character Varying NOT NULL,
"email" Character Varying NOT NULL,
"sifre" Character Varying NOT NULL,
"yetki_seviyesi" Integer NOT NULL,
PRIMARY KEY ( "kisino" ) ); ;
Uye: (kisino 1 olamayan herkes) 
CREATE TABLE "public"."uye" ( 
"kisino" Integer DEFAULT nextval('kisi_kisino_seq'::regclass) NOT NULL,
"ad" Character Varying NOT NULL,
"soyad" Character Varying NOT NULL,
"email" Character Varying NOT NULL,
"sifre" Character Varying NOT NULL,
"uye_tipi" "public"."uye_tipi_enum" DEFAULT 'standart'::uye_tipi_enum NOT NULL,
PRIMARY KEY ( "kisino" ) );
